---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "192.168.4.200"
  apiServerPort: 6443
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  # - role: worker
...
